name: pylsl
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - libcxx=13.0.1
  - libffi=3.3
  - liblsl=1.16.0
  - ncurses=6.3
  - openssl=1.1.1n
  - pip=21.2.4
  - pugixml=1.11.4
  - python=3.9.12
  - python_abi=3.9
  - readline=8.1.2
  - setuptools=61.2.0
  - sqlite=3.38.2
  - tk=8.6.11
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - attrs==21.4.0
    - bottleneck==1.3.4
    - charset-normalizer==2.0.12
    - colorama==0.4.4
    - coloredlogs==15.0.1
    - cython==0.29.28
    - decorator==4.4.2
    - frozenlist==1.3.0
    - humanfriendly==10.0
    - idna==3.3
    - jinja2==3.1.1
    - jsonschema==4.4.0
    - markupsafe==2.1.1
    - multidict==6.0.2
    - networkx==2.5.1
    - numexpr==2.8.1
    - numpy==1.22.3
    - packaging==21.3
    - pandas==1.4.2
    - pylsl==1.15.0
    - pyparsing==3.0.8
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - python-dotenv==0.20.0
    - python-osc==1.8.0
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - scipy==1.8.0
    - six==1.16.0
    - tables==3.7.0
    - timeflux==0.11.1
    - timeflux-example==0.1.2
    - timeflux-ui==0.4.0
    - xarray==2022.3.0
    - yarl==1.7.2
