name: pylsl
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - blosc=1.21.1
  - bottleneck=1.3.4
  - bzip2=1.0.8
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - git=2.34.1
  - hdf5=1.12.1
  - intel-openmp=2021.4.0
  - krb5=1.19.3
  - libcurl=7.82.0
  - liblsl=1.16.0
  - libssh2=1.10.0
  - libzlib=1.2.11
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numexpr=2.8.1
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1n
  - packaging=21.3
  - pip=21.2.4
  - pugixml=1.11.4
  - pyparsing=3.0.8
  - pytables=3.7.0
  - python=3.9.12
  - python_abi=3.9
  - setuptools=61.2.0
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.38.2
  - tzdata=2022a
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - zlib=1.2.11
  - pip:
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - attrs==21.4.0
    - charset-normalizer==2.0.12
    - colorama==0.4.4
    - coloredlogs==15.0.1
    - cython==0.29.28
    - decorator==4.4.2
    - frozenlist==1.3.0
    - humanfriendly==10.0
    - idna==3.3
    - jinja2==3.1.1
    - joblib==1.1.0
    - jsonschema==4.4.0
    - markupsafe==2.1.1
    - multidict==6.0.2
    - networkx==2.5.1
    - pandas==1.4.2
    - pylsl==1.15.0
    - pyreadline3==3.4.1
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - python-dotenv==0.20.0
    - python-osc==1.8.0
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - threadpoolctl==3.1.0
    - timeflux==0.11.1
    - timeflux-example==0.1.2
    - timeflux-ui==0.4.0
    - xarray==2022.3.0
    - yarl==1.7.2
